### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected error

### ISSUE THREAD

**Issue by infctr** [ai/size-limit#146]
I'm trying to set up `size-limit` for an existing project which is based on CRA with a couple of tweaks, but I'm getting the following error. 

```sh
❯ yarn size
yarn run v1.17.3
warning ../../package.json: No license field
$ yarn build && size-limit
warning ../../package.json: No license field
$ react-scripts build
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Compiled successfully.

File sizes after gzip:

  396.15 KB  build/static/js/2.3cba6e21.chunk.js
  76.91 KB   build/static/js/main.8e80c2e7.chunk.js
  7.55 KB    build/static/js/7.1ea4c9fa.chunk.js
  7.08 KB    build/static/js/25.be2e9d01.chunk.js
  6.76 KB    build/static/js/3.4057f02a.chunk.js
  6.24 KB    build/static/js/16.0eb7bbd2.chunk.js
  6.01 KB    build/static/js/21.8d9c8948.chunk.js
  5.99 KB    build/static/js/14.5123961e.chunk.js
  5.97 KB    build/static/js/26.a9438a5b.chunk.js
  5.95 KB    build/static/js/4.dc57c9b5.chunk.js
  5.79 KB    build/static/js/31.1b52b45e.chunk.js
  5.78 KB    build/static/js/18.a9bd853f.chunk.js
  5.76 KB    build/static/js/30.618e2b25.chunk.js
  5.74 KB    build/static/js/29.36acb135.chunk.js
  5.68 KB    build/static/js/17.b32ef675.chunk.js
  5.65 KB    build/static/js/11.b73e74dc.chunk.js
  5.64 KB    build/static/js/12.0c29e2fc.chunk.js
  5.61 KB    build/static/js/24.e3c3e2ed.chunk.js
  5.6 KB     build/static/js/6.aaaab9f3.chunk.js
  5.58 KB    build/static/js/27.5ed730c1.chunk.js
  5.53 KB    build/static/js/22.df4c7604.chunk.js
  5.49 KB    build/static/js/9.c5ad56dd.chunk.js
  5.48 KB    build/static/js/13.c55360c1.chunk.js
  5.42 KB    build/static/js/19.7c1b9920.chunk.js
  5.39 KB    build/static/js/23.0d931073.chunk.js
  5.38 KB    build/static/js/15.d421a0e3.chunk.js
  5.29 KB    build/static/js/5.7e9507a0.chunk.js
  5.27 KB    build/static/js/28.632677af.chunk.js
  5.25 KB    build/static/js/20.0d92b078.chunk.js
  5.24 KB    build/static/js/10.d80e1b45.chunk.js
  4.97 KB    build/static/js/8.1b5ad7db.chunk.js
  4.01 KB    build/static/css/2.827b0ffa.chunk.css
  1.44 KB    build/static/js/runtime~main.715057ca.js

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  https://bit.ly/CRA-deploy

(node:69563) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:69563) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:69563) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:69563) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added to [process]. Use emitter.setMaxListeners() to increase limit
TimeoutError: waiting for target failed: timeout 30000ms exceeded
    at Function.waitWithTimeout (/Users/infctr/Projects/react-cra/node_modules/puppeteer-core/lib/helper.js:224:26)
    at Browser.waitForTarget (/Users/infctr/Projects/react-cra/node_modules/puppeteer-core/lib/Browser.js:214:27)
    at Browser.<anonymous> (/Users/infctr/Projects/react-cra/node_modules/puppeteer-core/lib/helper.js:112:23)
    at Launcher.launch (/Users/infctr/Projects/react-cra/node_modules/puppeteer-core/lib/Launcher.js:184:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createChromeTrace (/Users/infctr/Projects/react-cra/node_modules/estimo/src/create-chrome-trace.js:20:19)
    at async estimoJsMode (/Users/infctr/Projects/react-cra/node_modules/estimo/src/js-mode/index.js:9:17)
    at async estimo (/Users/infctr/Projects/react-cra/node_modules/estimo/src/lib.js:38:32)
    at async getTime (/Users/infctr/Projects/react-cra/node_modules/@size-limit/time/get-running-time.js:18:14)
    at async Promise.all (index 24)
  -- ASYNC --
    at Browser.<anonymous> (/Users/infctr/Projects/react-cra/node_modules/puppeteer-core/lib/helper.js:111:15)
    at Launcher.launch (/Users/infctr/Projects/react-cra/node_modules/puppeteer-core/lib/Launcher.js:184:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createChromeTrace (/Users/infctr/Projects/react-cra/node_modules/estimo/src/create-chrome-trace.js:20:19)
    at async estimoJsMode (/Users/infctr/Projects/react-cra/node_modules/estimo/src/js-mode/index.js:9:17)
    at async estimo (/Users/infctr/Projects/react-cra/node_modules/estimo/src/lib.js:38:32)
    at async getTime (/Users/infctr/Projects/react-cra/node_modules/@size-limit/time/get-running-time.js:18:14)
    at async Promise.all (index 24)
    at async sum (/Users/infctr/Projects/react-cra/node_modules/@size-limit/time/index.js:8:11)
    at async Object.step80 (/Users/infctr/Projects/react-cra/node_modules/@size-limit/time/index.js:27:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

.size-limit.js
```js
module.exports = [
  {
    path: 'build/static/js/*.js',
    limit: '800 KB',
  },
]
```

```sh
❯ node -v
v12.13.0
```

Not sure whether the issue is directly related to `size-limit`, is there any known workaround or am I missing something?

**Comment by ai** [comment]
Check the size of all files `build/static/js/*.js`. Size Limit could takes also files from previous build and it became too many files at all.

Also, I need your `package.json` to find what present are you using.

**Comment by infctr** [comment]
It's 2.1KB, 32 files total. The build folder is cleaned on each run, so there's no way there are too many files. I use `"@size-limit/preset-app": "^2.2.0"`

**Comment by ai** [comment]
Fast solution is to switch to `@size-limit/file` to not call Puppeteer (but you will loose time metric).

For real solution, I need a way to reproduce the issue.

**Comment by infctr** [comment]
Unfortunately I can't share a repro because of the disclosure issues. 

I'll close this for now, as `@size-limit/file` seems to do the task

**Comment by timocov** [comment]
I just faced the same issue with latest versions of `size-limit` and `@size-limit/file` (without any preset).

I'm trying to integrate `size-limit` to https://github.com/tradingview/lightweight-charts and run the following script:

```javascript
const sizeLimit = require('size-limit');
const filePlugin = require('@size-limit/file');

sizeLimit([filePlugin], ['dist/lightweight-charts.esm.production.js']).then(result => {
	console.log(result);
});
```

Is there any solution for that? The repro is pretty easy, I just run `sizeLimit` via JS API with `@size-limit/file` plugin and provide any file.

**Comment by timocov** [comment]
It seems that the issue a bit different and is about `file` plugin itself. I'll create another issue for that. Sorry.

**Comment by ai** [comment]
@timocov 

1. Start with Size Limit CLI. Maybe it is a problem of JS APII(which is not really user-friendly)
2. If you still will have a problem, open another issue
