### ISSUE TITLE
Error: No valid exports main found for '/home/circleci/site/node_modules/nanoid'

### ISSUE THREAD

**Issue by pustovalov** [ai/size-limit#172]
Updates size-limit from 4.4.1 to 4.4.2

```
circleci@78d1750ce013:~/site$ yarn size
yarn run v1.19.2
$ yarn size-limit
$ /home/circleci/site/node_modules/.bin/size-limit
 ERROR  Error: No valid exports main found for '/home/circleci/site/node_modules/nanoid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/circleci/site/node_modules/@size-limit/webpack/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
circleci@78d1750ce013:~/site$

circleci@78d1750ce013:~/site$ cat /home/circleci/site/node_modules/@size-limit/webpack/index.js
let SizeLimitError = require('size-limit/size-limit-error')
let { promisify } = require('util')
let { nanoid } = require('nanoid')
let { tmpdir } = require('os')
let { join } = require('path')
let rimraf = promisify(require('rimraf'))

```
```
circleci@78d1750ce013:~/site$ yarn why nanoid
yarn why v1.19.2
[1/4] Why do we have the module "nanoid"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "nanoid@3.0.2"
info Reasons this module exists
   - "@size-limit#preset-small-lib#@size-limit#webpack" depends on it
   - Hoisted from "@size-limit#preset-small-lib#@size-limit#webpack#nanoid"
info Disk size without dependencies: "92KB"
info Disk size with unique dependencies: "92KB"
info Disk size with transitive dependencies: "92KB"
info Number of shared dependencies: 0
Done in 0.61s.
circleci@78d1750ce013:~/site$ yarn why size-limit
yarn why v1.19.2
[1/4] Why do we have the module "size-limit"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "size-limit@4.4.2"
info Has been hoisted to "size-limit"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "828KB"
info Disk size with unique dependencies: "1.54MB"
info Disk size with transitive dependencies: "11.7MB"
info Number of shared dependencies: 96
Done in 0.69s.
circleci@78d1750ce013:~/site$ yarn why @size-limit/preset-small-lib
yarn why v1.19.2
[1/4] Why do we have the module "@size-limit/preset-small-lib"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@size-limit/preset-small-lib@4.4.2"
info Has been hoisted to "@size-limit/preset-small-lib"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "28KB"
info Disk size with unique dependencies: "504KB"
info Disk size with transitive dependencies: "62.19MB"
info Number of shared dependencies: 176
Done in 1.05s.
```

**Comment by pustovalov** [comment]
but locally everything works

**Comment by ai** [comment]
It could be result of new ESM/CJS release system in Nano ID.

1. What version of Nano ID do you use?
2. What is your Size Limit config?

**Comment by pustovalov** [comment]
1. nanoid from `@size-limit#preset-small-lib#@size-limit#webpack#nanoid`: 3.0.2
2.
```
[
  {
    "path": "build/js/app.*.js",
    "limit": "4 KB",
    "webpack": false,
    "brotli": true
  },
  {
    "path": "build/js/vendors.*.js",
    "limit": "15 KB",
    "webpack": false,
    "brotli": true
  },
  {
    "path": "build/app.*.css",
    "limit": "10 KB",
    "webpack": false
  }
]

```

**Comment by ai** [comment]
What Node.js version do you use?

**Comment by pustovalov** [comment]
circleci: v13.3.0
local: v13.12.0

**Comment by pustovalov** [comment]
working on 

circle Node 12.16.1
circle Node 13.12.0

**Comment by ai** [comment]
Strange. I have the same version and everything works.

Can you check `node_modules`. Maybe it was corrupted?

Let’s start from `yarn cache clean && rm -Rf node_modules && yarn`.

**Comment by pustovalov** [comment]
Do you have Node.js v13.3? Because looks like it's not working only for this version

**Comment by ai** [comment]
I have 13.12. I afraid that there is not sense to support old Node.js 13 since it is not LTS.

Can you just update Node.js on Circle CI?

**Comment by pustovalov** [comment]
Yea, like I said before: https://github.com/ai/size-limit/issues/172#issuecomment-605735136

Thx for you help
