### ISSUE TITLE
Error: No valid exports main found for '<path>/node_modules/colorette'

### ISSUE THREAD

**Issue by gauravmakkar** [ai/size-limit#190]
yarn run v1.22.4
$ size-limit
internal/modules/cjs/loader.js:625
  throw e;
  ^

Error: No valid exports main found for '<PATH>/node_modules/colorette'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/<PATH>/node_modules/size-limit/bin.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
}
error Command failed with exit code 1.

**Comment by ai** [comment]
1. What Size Limit version do you use?
2. What Node.js version do you use?

**Comment by gauravmakkar** [comment]
size-limit version: 4.5.4
node.js version v13.5.0

**Comment by ai** [comment]
Node.js 13 has a bug. You need to update to Node.js >=13.7 or to Node.js 14.

**Comment by ai** [comment]
I changed `engines.node` https://github.com/ai/size-limit/commit/95d92fcc3e042ad8ef2f33d5b74892d0064e2eca and released the it in 4.5.5
