### ISSUE TITLE
Yarn 2 Berry Compat

### ISSUE THREAD

**Issue by lfender6445** [ai/size-limit#210]
- as a user of `yarn -v 2.4.0`
- i can run `yarn run size-limit` 

clone https://github.com/lfender6445/size-limit-berry for a working demonstration of the bug 

```
› yarn run size-limit
⠴ Running JS in headless ChromeTypeError: p.match is not a function
    at Function.resolveVirtual (/Users/lfender/source/size-limit-berry/.pnp.js:4206:21)
    at VirtualFS.mapToBase (/Users/lfender/source/size-limit-berry/.pnp.js:4243:22)
    at VirtualFS.fsMapToBase (/Users/lfender/source/size-limit-berry/.pnp.js:4163:19)
    at VirtualFS.writeFilePromise (/Users/lfender/source/size-limit-berry/.pnp.js:4040:46)
    at PosixFS.writeFilePromise (/Users/lfender/source/size-limit-berry/.pnp.js:4040:24)
    at Object.readProtocolStream (/Users/lfender/source/size-limit-berry/.yarn/cache/puppeteer-core-npm-5.5.0-f1c3bc7843-2ac92cb41a.zip/node_modules/puppeteer-core/lib/cjs/puppeteer/common/helper.js:254:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createChromeTrace (/Users/lfender/source/size-limit-berry/.yarn/unplugged/estimo-npm-2.2.2-d967483a84/node_modules/estimo/src/create-chrome-trace.js:97:7)
    at async processor (/Users/lfender/source/size-limit-berry/.yarn/unplugged/estimo-npm-2.2.2-d967483a84/node_modules/estimo/src/processor.js:78:19)
    at async estimo (/Users/lfender/source/size-limit-berry/.yarn/unplugged/estimo-npm-2.2.2-d967483a84/node_modules/estimo/src/lib.js:12:32)
✖ Running JS in headless Chrome
 ERROR  TypeError: Cannot read property 'javaScript' of undefined
    at getTime (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-b875eea979/node_modules/@size-limit/time/get-running-time.js:29:22)
    at async getThrottling (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-b875eea979/node_modules/@size-limit/time/get-running-time.js:39:16)
    at async getRunningTime (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-b875eea979/node_modules/@size-limit/time/get-running-time.js:56:5)
    at async Promise.all (index 0)
    at async sum (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-b875eea979/node_modules/@size-limit/time/index.js:8:11)
    at async Object.step80 (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-b875eea979/node_modules/@size-limit/time/index.js:28:23)
    at async Promise.all (index 0)
    at async step (/Users/lfender/source/size-limit-berry/.yarn/cache/size-limit-npm-4.9.1-21b9cf9b01-f6b194fd15.zip/node_modules/size-limit/calc.js:15:13)
    at async calc (/Users/lfender/source/size-limit-berry/.yarn/cache/size-limit-npm-4.9.1-21b9cf9b01-f6b194fd15.zip/node_modules/size-limit/calc.js:44:36)
    at async calcAndShow (/Users/lfender/source/size-limit-berry/.yarn/cache/size-limit-npm-4.9.1-21b9cf9b01-f6b194fd15.zip/node_modules/size-limit/run.js:62:7)

```

Yarn Berry changes the way the underlying node module fs works

> When using PnP, packages are stored and accessed directly inside the Zip archives from the cache. The PnP runtime (.pnp.cjs) automatically patches Node's fs module to add support for accessing files inside Zip archives. This way, you don't have to do anything special:

> https://yarnpkg.com/features/pnp#frequently-asked-questions

Some quick research suggests there might be type issues around JS files loaded thru puppeteer. That said, it might be a more appropriate issue for puppeteer-core, im just not fully confident yet.

**Comment by ai** [comment]
Can you remove `time` plugin (try using only `@size-limit/file` or `@size-limit/preset-small-libs`)

**Comment by lfender6445** [comment]
similar stack trace for that scenario 

see https://github.com/lfender6445/size-limit-berry/tree/preset-small-libs for details 

```
› yarn run size-limit
✔ Adding to empty webpack project
⠴ Running JS in headless ChromeTypeError: p.match is not a function
    at Function.resolveVirtual (/Users/lfender/source/size-limit-berry/.pnp.js:9413:21)
    at VirtualFS.mapToBase (/Users/lfender/source/size-limit-berry/.pnp.js:9450:22)
    at VirtualFS.fsMapToBase (/Users/lfender/source/size-limit-berry/.pnp.js:9370:19)
    at VirtualFS.writeFilePromise (/Users/lfender/source/size-limit-berry/.pnp.js:9247:46)
    at PosixFS.writeFilePromise (/Users/lfender/source/size-limit-berry/.pnp.js:9247:24)
    at Object.readProtocolStream (/Users/lfender/source/size-limit-berry/.yarn/cache/puppeteer-core-npm-5.5.0-f1c3bc7843-2ac92cb41a.zip/node_modules/puppeteer-core/lib/cjs/puppeteer/common/helper.js:254:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createChromeTrace (/Users/lfender/source/size-limit-berry/.yarn/unplugged/estimo-npm-2.2.2-d967483a84/node_modules/estimo/src/create-chrome-trace.js:97:7)
    at async processor (/Users/lfender/source/size-limit-berry/.yarn/unplugged/estimo-npm-2.2.2-d967483a84/node_modules/estimo/src/processor.js:78:19)
    at async estimo (/Users/lfender/source/size-limit-berry/.yarn/unplugged/estimo-npm-2.2.2-d967483a84/node_modules/estimo/src/lib.js:12:32)
    at async getTime (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-2a6d1e88f5/node_modules/@size-limit/time/get-running-time.js:18:14)
    at async getThrottling (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-2a6d1e88f5/node_modules/@size-limit/time/get-running-time.js:39:16)
    at async getRunningTime (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-2a6d1e88f5/node_modules/@size-limit/time/get-running-time.js:56:5)
    at async Promise.all (index 0)
    at async sum (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-2a6d1e88f5/node_modules/@size-limit/time/index.js:8:11)
    at async Object.step80 (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-2a6d1e88f5/node_modules/@size-limit/time/index.js:28:23)
✖ Running JS in headless Chrome
 ERROR  TypeError: Cannot read property 'javaScript' of undefined
    at getTime (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-2a6d1e88f5/node_modules/@size-limit/time/get-running-time.js:29:22)
    at async getThrottling (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-2a6d1e88f5/node_modules/@size-limit/time/get-running-time.js:39:16)
    at async getRunningTime (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-2a6d1e88f5/node_modules/@size-limit/time/get-running-time.js:56:5)
    at async Promise.all (index 0)
    at async sum (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-2a6d1e88f5/node_modules/@size-limit/time/index.js:8:11)
    at async Object.step80 (/Users/lfender/source/size-limit-berry/.yarn/unplugged/@size-limit-time-virtual-2a6d1e88f5/node_modules/@size-limit/time/index.js:28:23)
    at async Promise.all (index 0)
    at async step (/Users/lfender/source/size-limit-berry/.yarn/cache/size-limit-npm-4.9.1-21b9cf9b01-f6b194fd15.zip/node_modules/size-limit/calc.js:15:13)
    at async calc (/Users/lfender/source/size-limit-berry/.yarn/cache/size-limit-npm-4.9.1-21b9cf9b01-f6b194fd15.zip/node_modules/size-limit/calc.js:44:36)
    at async calcAndShow (/Users/lfender/source/size-limit-berry/.yarn/cache/size-limit-npm-4.9.1-21b9cf9b01-f6b194fd15.zip/node_modules/size-limit/run.js:62:7)
    at async module.exports (/Users/lfender/source/size-limit-berry/.yarn/cache/size-limit-npm-4.9.1-21b9cf9b01-f6b194fd15.zip/node_modules/size-limit/run.js:67:5)
````

**Comment by lfender6445** [comment]
looks like time is required for both scenarios

```
size-limit-berry on file
› cat package.json -p
{
  "name": "size-limit-berry",
  "dependencies": {
    "@size-limit/file": "^4.9.1",
    "size-limit": "^4.9.1"
  }
}
(base)
size-limit-berry on file
› yarn run size-limit
 ERROR  Add @size-limit/time plugin to use time limit
(base)
```

**Comment by ai** [comment]
@lfender6445 remove `time` from Size Limit config

**Comment by lfender6445** [comment]
```diff
diff --git a/.size-limit.js b/.size-limit.js
index 4945992..8e36635 100644
--- a/.size-limit.js
+++ b/.size-limit.js
@@ -2,7 +2,7 @@ module.exports = [
   {
     path: "postcss.config.js",
     // import: "{ createStore }",
-    limit: "500 ms"
+    // limit: "500 ms"
   }
 ]
```

```sh
› yarn run size-limit

  Size: 266 B gzipped

```

got back a size

**Comment by ai** [comment]
OK. So the problem is with `time` plugin. Here are 3 options:

1. You can move to size limit instead of time limit.
2. You can send PR to `estimo` to fix Yarn 2 Zero-Install support.
3. You can add `nodeLinker` option to Yarn 2 to generate classic `node_modules`

**Comment by lfender6445** [comment]
yeah

i think its mostly an issue with puppeteer and yarn, not really estimo

will close this out but might revisit with some commentary when i've had more time to explore it
