### ISSUE TITLE
Timed out after 30000 ms while trying to connect to the browser

### ISSUE THREAD

**Issue by unional** [ai/size-limit#300]
This is related to: https://github.com/ai/size-limit/issues/209

It fails intermittently. This one fails on Windows, node 14:

```
@mocktomata/framework:size: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r982053 is guaranteed to work.
@mocktomata/framework:size:     at Timeout.onTimeout (D:\a\mocktomata\mocktomata\node_modules\.pnpm\puppeteer-core@13.7.0\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:252:20)
@mocktomata/framework:size:     at listOnTimeout (internal/timers.js:557:17)
@mocktomata/framework:size:     at processTimers (internal/timers.js:500:7)
@mocktomata/framework:size: ✖ Running JS in headless Chrome
@mocktomata/framework:size:  ERROR  TypeError: Cannot read property 'javaScript' of undefined
@mocktomata/framework:size:     at getTime (D:\a\mocktomata\mocktomata\node_modules\.pnpm\@size-limit+time@8.0.1_size-limit@8.0.1\node_modules\@size-limit\time\get-running-time.js:29:22)
```

https://github.com/mocktomata/mocktomata/actions/runs/3248959225/jobs/5330798275

I notice it is using `puppeteer-core@13.7.0`

Maybe updating it to 19 would help.

Yes, this is an issue with https://github.com/mbalabash/estimo

Will create an issue there to link and track. thx

**Comment by ai** [comment]
I can only wait a reply from `estimo` maintainer

**Comment by unional** [comment]
No problem, just also adding the issue here so that other people can find this issue.

**Comment by mbalabash** [comment]
Hey @ai
Is it possible to break compatibility with node-12 in estimo?
