### ISSUE TITLE
Unknown browser query > 1% in alt-EU error

### ISSUE THREAD

**Issue by alexander-schranz** [ai/size-limit#77]
Get the error `Unknown browser query > 1% in alt-EU error` with:

```
{
  "scripts": {
    "lint:size": "size-limit"
  },
  "size-limit": [
    {
      "path": "./../../public/website/build/js/main.js",
      "limit": "42 KB"
    },
    {
      "path": "./../../public/website/build/css/main.css",
      "limit": "5 KB"
    }
  ],
  "devDependencies": {
    "size-limit": "^0.21.0"
  },
  "browserslist": [
    "> 1% in alt-EU",
    "last 2 versions"
  ]
}

```

<details>
<summary>Whole Error</summary>
ERROR in /public/website/build/css/main.css (/node_modules/css-loader??ref--5-1!/public/website/build/css/main.css)
Module build failed (from /node_modules/css-loader/index.js):
BrowserslistError: Unknown browser query `> 1% in alt-EU`
at error (/node_modules/caniuse-api/node_modules/browserslist/index.js:37:11)
at /node_modules/caniuse-api/node_modules/browserslist/index.js:222:9
at Array.forEach (<anonymous>)
at browserslist (/node_modules/caniuse-api/node_modules/browserslist/index.js:196:13)
at cleanBrowsersList (/node_modules/caniuse-api/dist/utils.js:56:59)
at setBrowserScope (/node_modules/caniuse-api/dist/index.js:29:43)
at Object.<anonymous> (/node_modules/caniuse-api/dist/index.js:91:1)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:7:19)
at Module._compile (module.js:652:30)
@ /public/website/build/css/main.css 2:14-92
@ multi /public/website/build/css/main.css
at runWebpack.then.stats (/assets/website/node_modules/size-limit/index.js:220:15)
at <anonymous>
error Command failed with exit code 1.
</summary>

**Comment by ai** [comment]
Hi. It is not Size Limit will, but Browserslist error (likely, I am maintainer of both tools 😄).

Check out all Browserslist version in `npm ls`

**Comment by alexander-schranz** [comment]
caniuse api looks like this

```
│ │ │ ├─┬ caniuse-api@3.0.0
│ │ │ │ ├─┬ browserslist@4.1.1
│ │ │ │ │ ├── caniuse-lite@1.0.30000885 deduped
│ │ │ │ │ ├── electron-to-chromium@1.3.67
│ │ │ │ │ └─┬ node-releases@1.0.0-alpha.11
│ │ │ │ │   └── semver@5.5.1 deduped
```

**Comment by alexander-schranz** [comment]
@ai not sure which package did block the upgrade but after upgrading all packages in my package.json it works correctly:

```
│ │ │ ├─┬ caniuse-api@3.0.0
│ │ │ │ ├── browserslist@4.3.4 deduped
│ │ │ │ ├── caniuse-lite@1.0.30000904 deduped
│ │ │ │ ├── lodash.memoize@4.1.2
│ │ │ │ └── lodash.uniq@4.5.0
```

 Thank for your time!

**Comment by ai** [comment]
Sorry, have no idea. Locally everything works.

Try to debug `node_modules/caniuse-api/node_modulesbrowserslist/index.js`. It should be simple JS file.
