### ISSUE TITLE
Errors when trying to call `size-limit -h` or `size-limit --help`

### ISSUE THREAD

**Issue by pdehaan** [ai/size-limit#9]
### Steps to reproduce:
1. Install `size-limit` as devDep.
1. Run `$(npm bin)/size-limit --help` or create an npm script in package.json that calls `size-limit --help`.

### Actual results:

```sh
$ npm run size:help

> firefox-send@1.0.4 size:help /Users/pdehaan/dev/github/mozilla/something-awesome
> size-limit --help

/Users/pdehaan/dev/github/mozilla/something-awesome/node_modules/size-limit/cli.js:27
  .alias('help', 'h')
   ^

TypeError: yargs.usage(...).option(...).option(...).version(...).help(...).alias is not a function
    at Object.<anonymous> (/Users/pdehaan/dev/github/mozilla/something-awesome/node_modules/size-limit/cli.js:27:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! firefox-send@1.0.4 size:help: `size-limit --help`
npm ERR! Exit status 1
```

**Comment by ai** [comment]
Should be related with https://github.com/ai/size-limit/issues/10
